[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  publish = "."
  functions = "netlify/functions"

[functions]
  external_node_modules = ["pdfjs-dist"]

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs22.x"