[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  publish = "."
  functions = "netlify/functions"

[functions]
  external_node_modules = ["@napi-rs/canvas", "pdf-parse", "pdfjs-dist"]